### ISSUE TITLE
[user-service]회원 가입 API

### ISSUE THREAD

**Issue by re-mora** [choi-ys/msa-with-spring-cloud#22]
### TODO
- 의존성 추가
   - [ ] H2 Database 및 Spring Data JPA 의존성 추가 및 설정
   - [ ] 인증/인가를 위한 Spring Security 의존성 추가 및 설정

- 회원가입 API 구현
  - [ ] 사용자 요청 수신을 위한 객체 및 Controller 구현 (유효성검사)
  - [ ] 사용자 영속처리를 위한 Entity 및 Service & Repository 구현
  - [ ] 회원가입 응답을 위한 객체 정의

---
### 구현 내용

> 요청: POST /users

> 요청 항목
- 이메일
- 비밀번호
- 이름

> 응답 항목
- 회원 번호
- 회원 이메일
- 회원 이름

> 처리 사항
- JSR 380 Annotations를 이용한 객체 binding 시점에 validation 진행
- 공통 에러 응답을 위한 ErrorResponse 정의
- 공통 예외 처리를 위한 GlobalExceptionHandler 구현
- Spring Security의 BCryptPasswordEncoder를 이용한 비밀번호 항목 암호화

---

### Reference URL
- [spring initializr](https://start.spring.io/)
- [maven central](https://mvnrepository.com/repos/central)
