### ISSUE TITLE
설정 중앙화를 위한 Configuration Service Project 생성

### ISSUE THREAD

**Issue by re-mora** [choi-ys/msa-with-spring-cloud#49]
- application 구동에 필요한 구성정보가 기술된 application.yml의 내용 변경 시, 변경된 내용의 적용을 위해 빌드 후 배포 과정이 동반됨
- 이를 해결하기 위해 Configuration Service에서 application 구동에 필요한 구성정보를 주입 받아 application을 구동함으로써 코드와 설정파일을 분리
- 효과 :
  - application 구동에 필요한 구성정보를 기술한 application.yml의 내용을 코드와 분리
  - application 구동 profiles 별 구성 정보 주입

### Spring Cloud Config
- 분산 시스템에서 서버, 클라이언트 구성에 필요한 설정 정보(application.,yml)을 외부 시스템에서 관리함으로써 코드와 구성 정보를 분리
- 하나의 중앙화 된 저장소에 구성 요소를 집중하여 관리 포인트 단일화
- 설정 정보 변경에 따른 Application 빌드, 배포 과정 생략
- Application 구동 profiles 별 구성 정보 주입 가능
- External Configuration Repository의 정보를 제공받고자 하는 micro service에게 전달

### 필요 의존성
```groovy
dependencies {
  implementation 'org.springframework.cloud:spring-cloud-config-server'
}
```

### 설정
entryPoint
```java
@SpringBootApplication
@EnableConfigServer
public class ConfigServiceApplication {
    public static void main(String[] args) {
        SpringApplication.run(ConfigServiceApplication.class, args);
    }
}
```
configurations
```yaml
server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: {git repository url}
```

### Example Spring config server configurations

> http://localhost:8888/datasource/default
```json
{
  "name": "datasource",
  "profiles": [
    "default"
  ],
  "label": null,
  "version": "4d6bf163f527e23681223415786355919b954637",
  "state": null,
  "propertySources": [
    {
      "name": "https://github.com/choi-ys/msa-with-spring-cloud-configuration/datasource.yml",
      "source": {
        "datasource.url": "jdbc:h2:mem:test_db;DB_CLOSE_ON_EXIT=FALSE",
        "datasource.driver-class-name": "org.h2.Driver",
        "datasource.username": "sa",
        "datasource.password": ""
      }
    }
  ]
}
```
- name : application-name 정보
- profiles : 해당 application설정 정보의 profiles 정보
- version : 해당 configuraion의 version 정보
- propertySources
  - name : configurations location 정보
  - source
     - configurations content 정보 
---
### TODO
- [ ] Configuration이 저장된 Public Git Repository의 configuration 정보 조회
  - [ ] External git repository : https://github.com/choi-ys/msa-with-spring-cloud-configuration 
  - [ ] GET /{configuration-name}/profile = ex) http://localhost:8888/datasource/default
- [ ] Configuration이 저장된 Private Git Repository의 configuration 정보 조회
- [ ] Private Git Repository에 저장된 configurations을 공개키 방식으로 암호화
- [ ] 공개키 방식으로 암호화된 configurations 조회 시 복호화된 configurations 조회

---
### Reference URL
- [Official:cloud.spring.io:spring-cloud-config](https://cloud.spring.io/spring-cloud-config/reference/html/)
